### PR TITLE
Fetch users and shells from AccountsService using D-Bus

### LINKED ISSUE #152: Unable to hide user accounts
I'm not sure if I'm looking in the wrong place but I can't find a way to hide user accounts from the list. 
I've tried marking these accounts as system in `/var/lib/AccountsService/users/` as I have read some display managers might respect it but regreet doesn't seem to.

Context: I have a couple of user accounts for testing purposes or running some specific software. These accounts are not system accounts, they have home directories and their own DEs and everything else the same as any other normal account . But I login into them so infrequently that I'd like to hide them from the list, so it wouldn't clutter the list and I could always just manually enter the login by hand when I actually needed to.

Is this feature just not implemented yet?

### PR DESCRIPTION
**Pull request by SergeyKasmy**
This PR removes the old `getpwent()` related code with manual login.defs UID filtering and replaces it with the [AccountsService API](https://www.freedesktop.org/wiki/Software/AccountsService/) that most other display managers and DEs use.

This fixes #152 as accounts can now be hidden by creating a `/var/lib/AccountsService/users/<username>` file with
```
[User]
SystemAccount=true
```

I believe pretty much any modern Linux desktop PC has the AccountsService service but if necessary, I can bring the old code back as a runtime fallback or a cargo feature (though I really like how much relying purely on AccountsService cleaned up the code). 

PR suggestions/improvements are very welcome! 
(Especially considering this was my first time using the zbus crate).

Thanks!

### CODE REVIEW

**Comment by rharish101** [comment]
Tested it locally on my desktop with Arch (with Hyprland and Xfce), and it works.

Looking at the code being simplified, I'm very tempted to merge this, but I can't unless I'm sure that all current users have AccountsService and dbus installed. In particular, let's check these distros:
1. Arch (someone other than me)
2. NixOS
3. Void Linux
4. Debian

The rest should already have dbus and AccountsService. Which one do you use?

**Comment by SergeyKasmy** [comment]
> Tested it locally on my desktop with Arch (with Hyprland and Xfce), and it works.

I'm personally using Arch with Hyprland and Plasma and it works great. AccountsService seems to have been pulled as a dependency of KDE (plasma-desktop & plasma-meta) and flatpak.

> but I can't unless I'm sure that all current users have AccountsService and dbus installed

I'm assuming users that don't use flatpaks and use a simple compositor like Hyprland or Sway won't have AccountsService installed.

D-Bus on the other hand is a must for any desktop Linux machine, so I don't see a world where one would need a GUI desktop manager without using any actual desktop Linux apps.

We could just say that AccountsService is a dependency of ReGreet as it's not such an unreasonable ask. It's already a dependency of GDM and plasma-login-manager (notably not lightdm or sddm - I have no idea how they handle this).

**Comment by rharish101** [comment]
> D-Bus on the other hand is a must for any desktop Linux machine, so I don't see a world where one would need a GUI desktop manager without using any actual desktop Linux apps.

Perfect, then that's not an issue.

> We could just say that AccountsService is a dependency of ReGreet as it's not such an unreasonable ask. It's already a dependency of GDM and plasma-login-manager (notably not lightdm or sddm - I have no idea how they handle this).

Sounds good. I checked the package repos of those distros, and they all package accountsservice, so I think we can go ahead.

File: src/sysutil/accounts_service.rs [hunk 1]
```diff
@@ -0,0 +1,33 @@
+// SPDX-FileCopyrightText: 2022 Harish Rajagopal <harish.rajagopals@gmail.com>
```
Comment (rharish101) [inline src/sysutil/accounts_service.rs:1]: Well, since I didn't write anything in this file, it was all you, the copyright would legally belong to you, not to me. So could you instead replace it with your name?

File: src/sysutil.rs
Comment (rharish101) [inline src/sysutil.rs:1]: Also add your name here please. I'll later add the names of everyone else who contributed to this file.

File: Cargo.toml [hunk 2]
```diff
@@ -25,7 +25,6 @@ humantime-serde = "1.1.1"
 jiff = "0.1.14"
 lazy_static = "1.5.0"
```
Comment (rharish101) [inline Cargo.toml]: We don't use `lazy_static` anymore, so could you remove that dep?

File: src/sysutil.rs [hunk 3]
```diff
@@ -52,85 +56,48 @@ pub struct SysUtil {
...
-            if let Some(cmd) = shlex::split(entry.shell.as_str()) {
-                shells.insert(entry.name, cmd);
-            } else {
-                // Skip this user, since a missing command means that we can't use it.
-                warn!(
-                    "Couldn't split shell of username '{}' into arguments: {}",
-                    entry.name, entry.shell
-                );
-            };
+            shells.insert(user_name, shell);
```
Comment (rharish101) [inline src/sysutil.rs:93]: Is it guaranteed that the user's shell is just the path to the shell, or can it have some args as well? In case of the latter, we'd have to still use shlex, right?

**Review by rharish101 — CHANGES_REQUESTED** [review]
Almost good, just some minor nits and questions.

File: Cargo.toml (hunk 2 above)
Comment (rharish101) [reply Cargo.toml]: Oh, also `test-case`.

File: src/sysutil.rs
Comment (SergeyKasmy) [reply src/sysutil.rs:1]: Is it really feasible to add the name of each and every contributor to every source code file header? This would get messy very quickly the more people contribute. In my personal projects I usually just stick to the license and that's it. Just my 2 cents

Comment (rharish101) [reply src/sysutil.rs:1]: Hmm, good point, then I'll just add "ReGreet contributors" later (not part of this PR) or something.

File: src/sysutil.rs (hunk 3 above)
Comment (SergeyKasmy) [reply src/sysutil.rs:93]: Yesterday I read in some man doc that it must always be an absolute path to a binary and anything else is disallowed.

But now I've taken a look into [util-linux login's source](https://github.com/util-linux/util-linux/blob/2cc4450d8e93968cb159c24d45b5ebd0e42f1e0b/login-utils/login.c#L1485), and they seem to handle both. 

I should probably revert the shell change just to be safe.

Comment (SergeyKasmy) [reply src/sysutil.rs:93]: Interestingly enough, [greetd seems to just pass all the cmd elements](https://github.com/kennylevinsen/greetd/blob/1bf47d7b2029233361be3c772a66384bb54a458d/greetd/src/session/worker.rs#L241) as pretty much `format!(/bin/sh -c "exec {}", cmd.join(" "))` (almost exactly like util-linux login). So there's no point to parse the string if the string is going to be passed to a shell anyway. In this case we could get rid of shlex completely and everything should still work.

I'm assuming this is not an implementation detail and is not going to change though.

Comment (SergeyKasmy) [reply src/sysutil.rs:93]: Tried creating a user with a shell set to `/usr/bin/bash --noprofile`

```
removeme:x:1004:1004::/home/removeme:/usr/bin/bash --noprofile
```

and PAM wouldn't let me log in with this error:

```
Apr 11 19:21:25 zeus greetd[257548]: pam_shells(greetd:auth): User has an invalid shell '/usr/bin/bash --noprofile'
```

So I'm almost 100% sure it's not something we should be bothering with. 

I'd even go as far as avoid preprocessing the command at all and just letting greetd and PAM figure it out by themselves.

Comment (rharish101) [reply src/sysutil.rs:93]: Sounds good, thanks a lot for investigating.

**Comment by rharish101** [comment]
Thanks a lot for the PR!
