### PR TITLE
Fix slow session start

### LINKED ISSUE #18: Logging in... takes ~5 seconds
After typing in my password, actually starting the session takes around 5 seconds (about as long as it would take to tell me my password is wrong). During this time, the text changes to "Logging in..." and I can still control the mouse and type into the password field. I'm using the default config, and the contents of `/var/log/regreet/log` have nothing from recent boots.

### PR DESCRIPTION
**Pull request by JohnnyJayJay**
Fixes #18 

This PR changes the behaviour of ReGreet when the greeter is done and a session is supposed to be started. Before:

Ask greetd to start session
- on failure: display error but otherwise leave greeter in same state
- on success:
   1. Set user-session cache entry
   2. Save cache to disk
   3. Display "Logging In..." message
   4. Do nothing/wait for greetd to kill ReGreet process

Now:
1. Display "Logging in..." message
2. Set user-session cache entry
3. Save cache to disk
4. Ask greetd to start session
   - on success: exit process with code 0
   - on failure: invoke session cancel handler to reset ReGreet, display error

I think the fact that we save the cache even if the session start was not successful is no problem, given the lack of significance of this situation. But it is a thing that we could change according to [what I described](https://github.com/rharish101/ReGreet/issues/18#issuecomment-1484214083). Ideally the `LruCache` should implement `Clone` for this purpose. I don't think this is really necessary anymore.

### CODE REVIEW

File: src/gui/model.rs [hunk 1]
```diff
@@ -449,6 +450,22 @@ impl Greeter {
         for (k, v) in env {
             environment.push(format!("{}={}", k, v));
         }
+
+        self.updates.set_message("Logging in...".to_string());
```
Comment (rharish101) [inline src/gui/model.rs:454]: We can remove this message, since it'll never be shown. That's because if it succeeds, then we immediately exist. If it fails, we reset the message and then show the error message. In all cases, we never exit the function without the "Logging in..." message, so Relm4 never picks it up.

**Review by rharish101 — CHANGES_REQUESTED** [review]

**Comment by rharish101** [comment]
Just tested it. It's "blazingly fast 🚀" now.

**Review by rharish101 — APPROVED** [review]
